## <u>Question 1:<u/>
### Write the lines of code (without using direct built-in packages) to perform the feed forward computation for the architecture given below with the weights and bias given. Use the matrix-vector multiplication as the function in the feed forward computation of each layer ?

<img src="Q1.png" alt="Drawing" style="width: 400px;"/>

# <u>Ans:<u/>

### <u>Theory:<u/>

<img src="A1.png" alt="Drawing" style="width: 700px;"/>

<img src="A5.png" alt="Drawing" style="width: 800px;"/>

<img src="A20.png" alt="Drawing" style="width: 800px;"/>

<img src="A21.png" alt="Drawing" style="width: 800px;"/>

<img src="A3.png" alt="Drawing" style="width: 800px;"/>

In [2]:
import numpy as np
np.random.seed(42)

In [3]:
def neuron(f):#here we defined it for 
    out = np.exp(-f)
    sol = np.round(1/(1+out),2) #hense the activation function is sigmoidal function
    return sol

<img src="Q1.png" alt="Drawing" style="width: 400px;"/>

In [4]:
Input = np.array([[1],[-1]])
#Setting network parameters.
weight1 = np.array([[1,-1],[-2,1]])
bias1 = np.array([[1],[0]])
weight2 = np.array([[2,-2],[-1,-1]])
bias2 = np.array([[0],[0]])
weight3 = np.array([[3,-1],[-1,4]])
bias3 = np.array([[-2],[2]])

weights = [weight1,weight2,weight3]
bias = [bias1,bias2,bias3]
for i in range(len(weights)):
    #C = weights[i].dot(Input) + bias[i]
    C = np.dot(weights[i].transpose(),Input) + bias[i] #Here we are using matrix multipication as the functionality 
                                                       #In this feed forward computation of each layer.
    Input = neuron(C)
    print("Result after ",i+1,"st layer computation")
    print(Input)
Finaly = Input
print("Hence the computation of all the Hiden Layers is done and the result at the end of compuation is: ")
print(Finaly)

Result after  1 st layer computation
[[0.98]
 [0.12]]
Result after  2 st layer computation
[[0.86]
 [0.11]]
Result after  3 st layer computation
[[0.62]
 [0.83]]
Hence the computation of all the Hiden Layers is done and the result at the end of compuation is: 
[[0.62]
 [0.83]]


# <u>Question 2:<u/>
### Generalize the code with the design of the deep neural architecture details received as an input from the user. Use the random weights and bias to perform the feed forward computation for the architecture given by the user ?

#### <u>Ans:<u/>
    
    So, when we analyze this Question Completly from "Zero" to "till dead" we found the following steps as very usefull  and eassyly understandable for one to get an excellent Idea in "what is feed forward computaion in neural network ?", So lets dive into the steps involved in the process of formulating the architecture according to the given requirments mentioned in our question.
    
   ***Steps Involved in computation of Neural Network:***
    
        1. Getting input from user like what is the size of input and the what are the inputs the user want to feed to the neural network
        2. what is the 

In [5]:
def sigma(f):
    out = np.exp(-f)
    sol = 1/(1+out)
    #sol = np.round(1/(1+out),2) #hense the activation function is sigmoidal function
    return sol

In [6]:
C = int(input("Enter the size of input data you want to give: \n"))
D = np.array([[None]]*C)
for i in range(C):
    D[i] = int(input("number "+ str(i+1)+" : \n"))
D = np.int32(D)
print("Input data:\n",D)

A = int(input("How many number of layers you want to have in your architecture?\n"))
B = []
for i in range(A):
    s = int(input("Enter number of neurons you required in the layer_"+ str(i+1) +" :\n"))
    B.append(s)
B = np.int32(B)
print(B)

Enter the size of input data you want to give: 
4
number 1 : 
1
number 2 : 
2
number 3 : 
4
number 4 : 
5
Input data:
 [[1]
 [2]
 [4]
 [5]]
How many number of layers you want to have in your architecture?
4
Enter number of neurons you required in the layer_1 :
5
Enter number of neurons you required in the layer_2 :
4
Enter number of neurons you required in the layer_3 :
7
Enter number of neurons you required in the layer_4 :
56
[ 5  4  7 56]


In [8]:
np.random.seed(42)
for i in range(len(B)):
    weight = np.random.randint(-10,10,size=(C,B[i]))
    bias = np.random.randint(-10,10,size = (B[i],1))
    weight = weight.transpose()
    print("Weight' = \n",weight,"\nD = \n",D,"\nbias = \n",bias)
    E = weight.dot(D) + bias
    print("\nWeight*D + bias\n",E)
    D = sigma(E)
    C = len(D)
    print("\nResult at the end of hiden layer",(i+1)," is:\n",D)
    print("\n-------------------------------------------------------\n")
print("\nTherefor the fruite of this architecture is: \n",D)

Weight' = 
 [[ -4  -4  -3  -9  -1   1  -4   3   4  -8  -3  -7  -7   3   4 -10  -3  -8
   -4   1  -8  -8 -10   4  -4  -4   2   2   0   2  -3  -1   6  -9   6 -10
   -5  -6   5   5  -8  -2  -3  -8   6  -6   8 -10  -7   5  -9 -10   9 -10
   -5  -9]
 [  9   8  -8 -10   5   9  -2   7  -4   3  -7   7   3  -3   2  -4   0  -8
   -2  -9   1  -6  -6   4   6   2  -4  -5  -4  -2  -2   1   6  -8   6 -10
   -7   9   5  -8   8 -10 -10  -4  -9  -6   5   9  -5  -8  -8  -7  -3   5
   -5 -10]
 [  4   0  -9   1   4  -8  -4  -2   1   6  -9   1   5   5  -2  -2   8 -10
   -4 -10  -3   4   3  -1   9   4   8   1 -10  -8  -6   4   9   6  -9   8
    0  -9 -10   9   9  -3   0   5 -10  -2   5   0  -3   7   5 -10  -4   1
    2   4]
 [  0   0   1   1   4  -6   7  -9  -3  -7  -5  -9   4   2   4 -10   6  -6
   -2   5  -8   3  -4   2  -7   0  -9   1 -10  -4 -10  -2   1  -6  -9  -9
    6  -5  -2  -7  -4  -4   7   5   5  -2  -8   6   9   3  -2   3  -8   8
    8 -10]
 [ -3  -7  -5   6   8   8  -7   9   4   7  -1  -1  -3   