**From the array of values: [23, 45, 112, 150, 43, 254, 95, 8] filter those 
that are greater than 100** - greater_array is asked

In [4]:
import numpy as np

In [6]:
array_5 = np.array([23, 45, 112, 150, 43, 254, 95, 8])
array_5

array([ 23,  45, 112, 150,  43, 254,  95,   8])

Filter ? - I think it is get numbers what are greater than 100

In [9]:
greater_array = array_5[array_5>100]
greater_array

array([112, 150, 254])

In [13]:
array_5[np.where(array_5>100)]

array([112, 150, 254])

In [14]:
np.where(array_5>100)

(array([2, 3, 5], dtype=int64),)

Filter? = filter out ? - it means don'd show numbers that are greater than 100 only number what are less than 100

In [10]:
lesser_array = array_5[array_5<100]
lesser_array

array([23, 45, 43, 95,  8])