**Create any array of values and then normalize them - i.e. from 
each element of the array subtract the mean and divide by the 
standard deviation**

In [1]:
import numpy as np

In [4]:
array_8 = np.array([15, 2, 4, 2, 6, 18, 20, 5, 7, 1, 9, 2, 11, 5])
array_8

array([15,  2,  4,  2,  6, 18, 20,  5,  7,  1,  9,  2, 11,  5])

In [8]:
np.sort(array_8)

array([ 1,  2,  2,  2,  4,  5,  5,  6,  7,  9, 11, 15, 18, 20])

In [9]:
np.mean(array_8)

7.642857142857143

In [10]:
(array_8 - np.mean(array_8))

array([-6.64285714, -5.64285714, -5.64285714, -5.64285714, -3.64285714,
       -2.64285714, -2.64285714, -1.64285714, -0.64285714,  1.35714286,
        3.35714286,  7.35714286, 10.35714286, 12.35714286])

In [11]:
(array_8 - np.mean(array_8))/np.std(array_8)

array([-1.1146721 , -0.946872  , -0.946872  , -0.946872  , -0.6112718 ,
       -0.4434717 , -0.4434717 , -0.2756716 , -0.10787149,  0.22772871,
        0.56332891,  1.23452932,  1.73792962,  2.07352982])

In [13]:
np.std(array_8)  # standard deviation

5.959471966747472

In [15]:
np.size(array_8)

14

In [16]:
np.sum(array_8)

107

In [19]:
np.sqrt((np.sum((array_8-np.mean(array_8))**2))/(np.size(array_8)))  # standard deviation function same as np.std(), just tired out the function writing

5.959471966747472