In [1]:
import numpy as np

**Sample value from normal distribution (jaotus)**

In [3]:
np.random.normal()

-0.23388995188959802

In [11]:
np.random.normal(loc=4, scale=3, size=(6,2)) #loc=mean, scale=standard deviation, size-the shape of the returned array

array([[7.08542267, 7.54112517],
       [5.46917895, 0.51421917],
       [0.54104111, 0.14478193],
       [5.86446455, 6.5378308 ],
       [5.67195291, 3.07287282],
       [2.54340314, 0.57256271]])

**Sample value from uniform distribution**

In [12]:
np.random.uniform()

0.36736560026690557

**Sample integr value from the range**

In [14]:
np.random.randint(3, 30, size=6)

array([ 9, 24, 29, 22, 15, 26])

In [21]:
x = np.random.normal(loc=2, scale=3, size=500)

In [22]:
np.mean(x) #average value

2.0768225357950056

In [17]:
np.std(x)

3.1070579882452316

In [18]:
np.var(x)

9.653809342318505

In [25]:
y = 3 + 5 * x

In [26]:
np.corrcoef(x, y)

array([[1., 1.],
       [1., 1.]])

In [27]:
y = np.random.normal(loc=0, scale=1, size=500)

In [28]:
np.corrcoef(x, y)

array([[ 1.        , -0.00477362],
       [-0.00477362,  1.        ]])

In [29]:
y = 3 + 5 * x + np.random.normal(loc=0, scale=1, size=500)

In [30]:
np.corrcoef(x, y)

array([[1.        , 0.99765864],
       [0.99765864, 1.        ]])

In [31]:
y = 3 + 5 * x + np.random.normal(loc=0, scale=10, size=500)

In [32]:
np.corrcoef(x, y)

array([[1.        , 0.81857149],
       [0.81857149, 1.        ]])