In [2]:
import numpy as np

In [6]:
M = np.array([
 [1,2,3,9],
 [2,3,4,0],
 [3,4,5,1],
 [8,6,2,3],
])
M

array([[1, 2, 3, 9],
       [2, 3, 4, 0],
       [3, 4, 5, 1],
       [8, 6, 2, 3]])

**Matrix determinant**

In [7]:
np.linalg.det(M)

-19.999999999999925

**Inverse matrix**

In [8]:
np.linalg.inv(M)

array([[-7.50000000e-01, -9.50000000e+00,  8.25000000e+00,
        -5.00000000e-01],
       [ 1.10000000e+00,  1.48000000e+01, -1.29000000e+01,
         1.00000000e+00],
       [-4.50000000e-01, -6.10000000e+00,  5.55000000e+00,
        -5.00000000e-01],
       [ 1.00000000e-01, -2.00000000e-01,  1.00000000e-01,
        -2.22044605e-17]])

**Eigenvalues and eigenvectors**

In [9]:
np.linalg.eig(M)

(array([13.78960663, -6.31259431,  4.47160619,  0.05138149]),
 array([[-0.59287205, -0.79625908, -0.56704857,  0.50847644],
        [-0.25565909,  0.12070379,  0.48436199, -0.79460544],
        [-0.39317923,  0.11711319,  0.46172181,  0.33150885],
        [-0.65463827,  0.58110805, -0.4802732 ,  0.01248157]]))