In [1]:
import numpy as np

**Create a 4 by 4 matrix using numpy**

In [4]:
matrix1 = np.array([
    [2,4,7,5],
    [5,6,8,1],
    [7,7,1,3],
    [9,1,5,6]
])
matrix1

array([[2, 4, 7, 5],
       [5, 6, 8, 1],
       [7, 7, 1, 3],
       [9, 1, 5, 6]])

**Calculate its determinant**

In [5]:
np.linalg.det(matrix1)

2405.0

**Calculate its inverse matrix**

In [6]:
np.linalg.inv(matrix1)

array([[-0.13804574,  0.05779626,  0.01538462,  0.0977131 ],
       [ 0.05779626,  0.0029106 ,  0.12307692, -0.11018711],
       [ 0.02037422,  0.10893971, -0.10769231,  0.01871102],
       [ 0.18045738, -0.17796258,  0.04615385,  0.02286902]])

**Calculate its eigenvalues and eigenvectors**

In [7]:
np.linalg.eig(matrix1)

(array([19.07152254,  5.74005717, -3.45747642, -6.35410329]),
 array([[ 0.47177065,  0.13151436, -0.5555581 ,  0.59428552],
        [ 0.51008179, -0.57896196,  0.46572256,  0.25569482],
        [ 0.47060442, -0.16191191, -0.28190615, -0.74739507],
        [ 0.54385706,  0.7882205 ,  0.62847961, -0.15114728]]))