In [2]:
import numpy as np

**Create an array of values from 4 to 19**

In [4]:
array_1 = np.arange(4,20)
array_1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**Choose the values that are higher than 6 to form another array.**

In [6]:
another_array_1 = array_1[array_1>6]
another_array_1

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**Calculate the max value** is it the max value from array ? or sum of the elements in array?

In [7]:
array_1.max()

19

In [8]:
array_1.sum()

184

**Normalize the array by the sum of all its values** Cannot understand what is needed :( - is normalized a array with elements between 0 and 1 ?

In [9]:
array_1/(array_1.sum())

array([0.02173913, 0.02717391, 0.0326087 , 0.03804348, 0.04347826,
       0.04891304, 0.05434783, 0.05978261, 0.06521739, 0.07065217,
       0.07608696, 0.08152174, 0.08695652, 0.0923913 , 0.09782609,
       0.10326087])